---
- name: Ensure virtualenv is present
  yum:
    name: python-virtualenv
    state: present

- name: Install certbot into virtualenv
  pip:
    name:
      - certbot
      - idna<2.8,>=2.5
    virtualenv: /opt/certbot

- name: Install certbot DNS provider
  pip:
    name:
      - "certbot-{{ certbot_dns_provider }}"
    virtualenv: /opt/certbot
  when: certbot_dns_provider is defined

- name: Set Certbot script variable.
  set_fact:
    certbot_script: "/opt/certbot/bin/certbot"
