---
- name: Create the ssl-cert group if it doesn't exist
  group:
    name: "{{ certbot_ssl_group }}"
    state: present
    system: yes
  when: certbot_ssl_group is defined

- name: Write the certificate post-renewal hook script
  copy:
    content: |
        #!/bin/bash
        mkdir -p  /etc/ssl/private/
        chmod {{ certbot_ssl_private_dir_mode | default(750) }} /etc/ssl/private/
        chown root:ssl-cert /etc/ssl/private/
        # Chain
        cp /etc/letsencrypt/live/{{ certbot_hostname_override | default(certbot_domains[0]) }}/fullchain.pem /etc/ssl/certs/fullchain.pem
        chmod 644           /etc/ssl/certs/fullchain.pem
        chown root:ssl-cert /etc/ssl/certs/fullchain.pem
        # Cert
        cp /etc/letsencrypt/live/{{ certbot_hostname_override | default(certbot_domains[0]) }}/cert.pem      /etc/ssl/certs/cert.pem
        chmod 644           /etc/ssl/certs/cert.pem
        chown root:ssl-cert /etc/ssl/certs/cert.pem
        # Privkey
        cp /etc/letsencrypt/live/{{ certbot_hostname_override | default(certbot_domains[0]) }}/privkey.pem   /etc/ssl/private/privkey.pem
        chmod 640           /etc/ssl/private/privkey.pem
        chown root:ssl-cert /etc/ssl/private/privkey.pem
        # For each user, create custom version
        {% for user in certbot_share_key_users %}
        cp /etc/ssl/private/privkey.pem /etc/ssl/private/privkey-{{ user }}.pem
        chown {{ user }}: /etc/ssl/private/privkey-{{ user }}.pem
        {% endfor %}
        # Other
        {{ certbot_post_renewal }}
    dest: /etc/letsencrypt/renewal-hooks/post/ansible.sh
    owner: root
    group: root
    mode: "0755"
